[app]
name = "LMS"
port = 4001
env = "local"
timeout = 30

[database]
driver = "postgres"
name = "capstone-test"
address = "localhost"
port = 5432
username = "devpostgres"
password = "devpostgres"

[storage]
cloudname = "dr8volyui"
apikey = "828743457647186"
apisecret = "BcDKFLS8izAM18lgxF-vkFNPxD4"
uploadfolder = "lms"