name: CI

on:
  push:
    branches:
      - "development"

jobs:
  # build-app:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.17

  #     - name: Install dependencies
  #       run: go mod download

  #     - name: Verify module
  #       run: go mod verify

  #     # - name: Go testing
  #     #   run: |
  #     #     cd business
  #     #     go test -v ./...
  #     - name: Build go App
  #       run: go build -v ./...

  #     # - name: Check go vet linting
  #     #   run: go vet ./...

  build-docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            academytokyo/capstone
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push into docker registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ssh-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: get outputs tags from docker push
        run: |
          echo "{{ steps.build-docker-push.outputs.tags }}" 
